[metadata]
name = "dev-dirs"
description = "A channel to select from directories in ~/dev"
requirements = ["fd"]

[source]
command = [
  "fd -t d --max-depth 1 . ~/dev",
  "fd -t d --max-depth 1 . ~/dev/forks",
  "fd -t d --max-depth 1 . ~/dev/learning",
]

[preview]
command = "ls -la --color=always '{}'"
