[theme]
foreground = "#c0caf5"
background = "#1a1b26"
selection_foreground = "#c0caf5"
selection_background = "#283457"
border = "#565f89"
mode_foreground = "#1a1b26"
insert_mode_background = "#9ece6a"
normal_mode_background = "#e0af68"
