// Generated by Secure ShellFish - forwards OpenCode events to shellfish-notify.sh.
import { spawn } from 'node:child_process';

export const ShellfishNotifyPlugin = async () => ({
  event: async ({ event }) => {
    if (event?.type !== 'session.idle') return;

    const proc = spawn('/Users/dorian/.config/opencode/shellfish-notify.sh', ['opencode'], {
      stdio: ['pipe', 'ignore', 'ignore'],
    });
    proc.stdin.end(JSON.stringify(event.properties || {}));
  },
});
