// Generated by Secure ShellFish - forwards OpenCode events to shellfish-notify.sh.
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { Plugin } from '@opencode/plugin';

const notifyScript = fileURLToPath(new URL('../shellfish-notify.sh', import.meta.url));

const sameLocation = (eventLocation, pluginLocation) => {
  return (
    eventLocation?.directory === pluginLocation.directory && eventLocation?.workspaceID === pluginLocation.workspaceID
  );
};

const notifyShellfish = (payload) => {
  return new Promise((resolve) => {
    const proc = spawn(notifyScript, ['opencode'], {
      stdio: ['pipe', 'ignore', 'ignore'],
    });

    const finish = () => resolve();
    proc.on('error', finish);
    proc.on('close', finish);
    proc.stdin.on('error', finish);
    proc.stdin.end(JSON.stringify(payload));
  });
};

const ShellfishNotifyPlugin = Plugin.define({
  id: 'shellfish-notify',
  setup(ctx) {
    const controller = new AbortController();
    const subscription = (async () => {
      try {
        for await (const event of ctx.event.subscribe({ signal: controller.signal })) {
          if (event.type !== 'session.idle' || !sameLocation(event.location, ctx.location)) continue;
          await notifyShellfish(event.data);
        }
      } catch (error) {
        if (!controller.signal.aborted) {
          console.error('ShellFish notification event stream failed', error);
        }
      }
    })();

    return async () => {
      controller.abort();
      await subscription;
    };
  },
});

export default ShellfishNotifyPlugin;
