# '##::::'##:'####::'######::'########:
#  ###::'###:. ##::'##... ##: ##.....::
#  ####'####:: ##:: ##:::..:: ##:::::::
#  ## ### ##:: ##::. ######:: ######:::
#  ##. #: ##:: ##:::..... ##: ##...::::
#  ##:.:: ##:: ##::'##::: ##: ##:::::::
#  ##:::: ##:'####:. ######:: ########:
# ..:::::..::....:::......:::........::

# NOTE: cargo backends are slower because they compile from source. I usually
# prefer not to use those, but in some cases there is no ARM64 binary available
# via Aqua / Github - so we have to use cargo, in other cases, there are no
# pre-compiled binaries at all - in such cases we should check periodically if
# binaries were published or contribute a fix to pre-compile binaries for arm64.
#
# Tools with no ARM bins:
# - erdtree
# - vivid
# - du-dust
# - rnr
# - tlrc (tldr)

# For the same reason - sometimes github backend is selected when aqua is
# available, if the aqua backend gets the architecture wrong:
# - hyperfine

[tools]

"cargo:erdtree" = "latest"            # file system tree visualizer with icons and git support
"cargo:fastmod" = "latest"            # fast regex code modifications
"cargo:rnr" = "latest"                # batch rename files and directories
"cargo:tlrc" = "latest"               # a tldr client (man pages but better) written in Rust
"cargo:vivid" = "latest"              # generate color schemes for different tools
"github:ast-grep/ast-grep" = "latest" # a cli tool for searching and rewriting code using AST
"github:chmln/sd" = "latest"          # a modern alternative for sed with sensible defaults
"github:cli/cli" = "latest"           # GitHub CLI
"github:dkarter/lnr" = "latest"       # linear cli
"github:dlvhdr/diffnav" = "latest"    # A git diff pager based on delta but with a file tree, à la GitHub.
"github:joshmedeski/sesh" = "latest"  # tmux session manager
"github:mazznoer/lolcrab" = "latest"  # like lolcat, but written in Rust and with more features
"github:raine/workmux" = "latest"     # git worktree manager in tmux
"npm:@commitlint/cli" = "latest"      # linter for checking that commits are following conventional commits
"npm:neovim" = "latest"               # support for javascript plugins in neovim
"npm:opencode-ai" = "latest"          # the best AI agent wrapper
"npm:prettier" = "latest"             # code formatter (js, ts, json, yaml and more)
"npm:trash-cli" = "latest"            # rm -> system trash (cross platform)
"pipx:httpie" = "latest"              # modern, user-friendly CLI HTTP client
"pipx:neovim-remote" = "latest"       # allow controlling neovim remotely
"pipx:yq" = "latest"                  # like jq but for yaml files
bat = "latest"                        # modern `cat` with syntax highlighting
bun = "latest"                        # faster JS runtime
cargo-binstall = "latest"             # use pre-compiled binaries for rust tools (instead of compiling from source)
choose = "latest"                     # A human-friendly and fast alternative to cut and (sometimes) awk
claude-code = "latest"                # slop machine
colima = "latest"                     # container runtime for macOS and linux
delta = "latest"                      # nicer git diffs
deno = "2"                            # Deno programming language
docker-cli = "latest"                 # just the cli - for the backend I'll use orbstack or colima
elixir = "1.19.5-otp-28"              # Elixir programming language
erlang = "28"                         # Erlang programming language
fd = "latest"                         # modern `find`
fnox = "latest"                       # secrets manager
fx = "latest"                         # like jq, but allows interactive exploration and copying paths
fzf = "latest"                        # fuzzy finder
gitleaks = "latest"                   # git leaks is a tool for detecting and preventing hardcoded secrets like passwords, API keys, and tokens in git repositories
glow = "latest"                       # Render markdown on the CLI
go = "1.25"                           # Go programming language
gum = "latest"                        # CLI / scripting UI tools
jq = "latest"                         # pretty print and query json
lazygit = "latest"                    # Git TUI
lima = "latest"                       # linux virtual machines for macOS (used by colima)
lsd = "latest"                        # ls with icons and colors, like `exa` but with more features
lua-language-server = "latest"        # Lua Language Server
neovim = "stable"                     # the best text editor/IDE
node = "22"                           # Node.js programming language
pitchfork = "latest"                  # run multiple commands in parallel, with a nice UI
python = "3.12"                       # Python programming language
rebar = "latest"                      # build tool for Erlang (equivalent to mix in Elixir)
resvg = "latest"                      # svg rendering library and CLI tool (used by yazi)
ripgrep = "latest"                    # modern `grep`
ruby = "3"                            # Ruby programming language
rust = "1"                            # Rust programming language
slsa-verifier = "latest"              # security: verify SLSA provenance
starship = "latest"                   # command prompt styling
stylua = "latest"                     # formatter for lua
task = "latest"                       # run tasks (modern make alternative)
television = "latest"                 # fancy fuzzy finder with shell integration and "channels"
tmux = "latest"                       # terminal multiplexer
typos = "latest"                      # type checker alternative to codespell
usage = "latest"                      # generates completion scripts for various tools (including mise)
uv = "latest"                         # install python packages
yazi = "latest"                       # terminal file manager
zoxide = "latest"                     # a modern version of autojump

# allow specific asdf plugins when there's no other option
# docs: https://mise.jdx.dev/dev-tools/aliases.html
# list of asdf plugins that would normally be supported https://mise.jdx.dev/registry.html#tools
[tool_alias]
rebar = 'asdf:mise-plugins/mise-rebar'
redis = 'asdf:mise-plugins/mise-redis'

[settings]
# needed to enable ruby gems install
experimental = true
disable_backends = ["asdf"]
# use bun instead of npm when using npm:<package>
npm.bun = true

# use pre-compiled binaries (since compiling ruby is slow as hell)
ruby.compile = false

# get pre-compiled binaries for rust tools via cargo-binstall (instead of compiling from source)
cargo.binstall = true

# use pre-compiled binaries for python when available
python.compile = false
